"""
author: @guu8hc
"""

import os

from datetime import datetime

from settings import FILE_ENCONDING

try:
    from temp.extract import model
except ModuleNotFoundError:
    print("[ERROR] Model not found")

class Generator:
    """
    This class is responsible for generating the application code.
    """

    def __init__(self, filename):
        self.filename = filename
        self.dir = "./_out"
        self.content = ""

    def generate(self):
        """
        generate the file
        """
        print(f"[DEBUG] Generating file: {self.filename}")
        with open(os.path.join(self.dir, self.filename), 'w', encoding=FILE_ENCONDING) as file:
            self.build_header()
            self.build_content()
            file.write(self.content)

    def build_header(self):
        """
        build the header
        """
        self.content += '"""\nauthor: @guu8hc\n"""\n\n'
        self.content += "#!/usr/bin/env python3\n"
        self.content += "# -*- coding: utf-8 -*-\n"
        self.content += "\n"
        self.content += "# Generated by guu8hc\n"
        self.content += f"# Generated time: {datetime.now()}\n"

    def build_content(self):
        """
        build the content
        """
        try:
            for pdu in model["PDUS"]:
                self.content += f"{pdu} = {{\n"
                for key, value in model["PDUS"][pdu].items():
                    self.content += f"    '{key}': {value},\n"
                self.content += "}\n"
        except NameError:
            print("[ERROR] Model not found")
